language: clojure
lein: lein2
dist: trusty
matrix:
  include:
  - name: "libsodium 1.0.15"
    env: LIBSODIUM_VERSION=1.0.15
  - name: "libsodium 1.0.13"
    env: LIBSODIUM_VERSION=1.0.13
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.lein
    - $HOME/.m2
install:
  - wget https://github.com/lvh/libsodium-debs/raw/master/libsodium-${LIBSODIUM_VERSION}_amd64.deb
  - sudo dpkg -i libsodium-${LIBSODIUM_VERSION}_amd64.deb
script:
  - lein with-profile +test cljfmt check
  - lein with-profile +test kibit
  - lein with-profile +test eastwood || true
  - lein with-profile +test ancient || true
  - lein test

after_success:
  - lein with-profile +test cloverage --codecov
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
