language: clojure
lein: lein2
dist: trusty
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.lein
    - $HOME/.m2
install:
  - wget https://github.com/lvh/libsodium-debs/raw/master/libsodium-1.0.13_amd64.deb
  - sudo dpkg -i libsodium-1.0.13_amd64.deb
script:
  - lein with-profile +test cljfmt check
  - lein with-profile +test kibit
  - lein with-profile +test eastwood || true
  - lein test

after_success:
  - CLOVERAGE_VERSION=1.0.7-SNAPSHOT lein with-profile +test cloverage --codecov
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
